"""Round 3 checker mutants (2026-10-03; fixtures_r3.py): each reverts or overshoots one round 3 change. Same form as
checker_mutants.SRC, (name, module, old, new); checker_mutants appends this list. The frame rule's hole width and
small-frame limits only matter for guidance the round 3 prompt no longer writes (the round 2 entity and topic
wording), so they are pinned and mutated by the unit tests (tests/test_round3_fixes.py, unit-test mutant run)."""
import check_r3
import lexicons

SRC_R3 = [
    ("frame_off", check_r3, "m = rx.search(s) if rx else None", "m = None"),
    ("frame_lists_too", check_r3, 'if (t["intent"] or "").startswith(NATURAL_Q):', "if False:"),
    ("frame_gap_0", check_r3, "FRAME_GAP = 2", "FRAME_GAP = 0"),
    ("frame_min_req_2", check_r3, "FRAME_MIN_REQ = 3", "FRAME_MIN_REQ = 2"),
    ("frame_min_req_4", check_r3, "FRAME_MIN_REQ = 3", "FRAME_MIN_REQ = 4"),
    ("frame_keep_lead", check_r3, "    while toks and toks[0] in FRAME_LEAD:\n        toks.pop(0)\n", ""),
    ("told_off", check_r3, "m = L.TOLD_FRAME_RE.search(s)\n        if m and not any(", "m = None\n        if m and not any("),
    ("told_no_source_exempt", check_r3, 'in ("assistant", "tool") for v in _names(ctx)', "in () for v in _names(ctx)"),
    ("told_last_source", check_r3, "for j in sorted(ctx.text) if j < i and ctx.has(j, v)",
     "for j in sorted(ctx.text, reverse=True) if j < i and ctx.has(j, v)"),
    ("forgot_off", check_r3, "if m and i not in abstain:", "if False:"),
    ("forgot_on_abstain", check_r3, "if m and i not in abstain:", "if m:"),
    ("own_error_off", check_r3, "if m and not any(f < i for f in fixes):", "if False:"),
    ("own_error_after_fix", check_r3, "if m and not any(f < i for f in fixes):", "if m:"),
    ("recap_checked", check_r3, 'if t.get("lookup_call") or i in recaps:', 'if t.get("lookup_call"):'),
    ("change_ack_earlier_checked", check_r3, "m = L.EARLIER_RE.search(s) if i not in acks else None",
     "m = L.EARLIER_RE.search(s)"),
    ("live_hedge_when_dropped", lexicons, ', r"when(?:ever)?"])', "])"),
    ("run_on_yes_dropped", lexicons, '"just", "yes", "oh",', '"just", "oh",'),
    ("earlier_off", check_r3, "if vals and not _said_before(ctx, vals, i - 1):", "if False:"),
    ("earlier_prev_line_ok", check_r3, "if vals and not _said_before(ctx, vals, i - 1):",
     "if vals and not _said_before(ctx, vals, i):"),
    ("live_off", check_r3, "for m in L.LIVE_RE.finditer(s):", "for m in []:"),
    ("live_hedge_off", check_r3, 'if not L.LIVE_HEDGE_RE.search(" ".join(s[:m.start()].split()[-3:]) + " " + m.group(0)):',
     "if True:"),
    ("live_hedge_match_only", check_r3, '" ".join(s[:m.start()].split()[-3:]) + " " + m.group(0)', "m.group(0)"),
    ("case_start_off", check_r3, "if m and m.group(0).islower():", "if False:"),
    ("case_lone_i_off", check_r3, "elif LONE_I_RE.search(s):", "elif False:"),
    ("case_lone_i_any_case", check_r3, 'LONE_I_RE = re.compile(r"(?<![A-Za-z\'])i(?![A-Za-z])")',
     'LONE_I_RE = re.compile(r"(?<![A-Za-z\'])i(?![A-Za-z])", re.I)'),
    ("run_on_off", check_r3, "for m in L.RUN_ON_RE.finditer(s):", "for m in []:"),
    ("run_on_join_ignored", check_r3, " and last[0] not in L.RUN_ON_JOIN:", ":"),
    ("run_on_punct_ignored", check_r3, "if prev and prev[-1].isalpha() and last", "if prev and last"),
    ("told_were_dropped", lexicons, "r\"you(?: were|'ve been| have been| had been) told\", ", ""),
    ("told_as_told_dropped", lexicons, 'r"as told(?! by you)",', 'r"zzqq",'),
    ("told_i_told_dropped", lexicons, "r\"i(?:'ve| have)? (?:already )?told you\",", "r\"zzqq\","),
    ("self_id_love_dropped", lexicons, 'r"i(?:\'d| would) (?:really |also |just |absolutely )?(?:love|enjoy) to(?! ',
     'r"zzqq(?:\'d| would) (?:really |also |just |absolutely )?(?:love|enjoy) to(?! '),
    ("self_id_love_any", lexicons, '(?:love|enjoy) to(?! (?:help|hear|know|learn|"', '(?:love|enjoy) to(?! (?:zzqq|"'),
    ("self_myself_dropped", lexicons, "r\"(?<!not )(?<!n't )(?<!never )(?:try|", "r\"zzqq(?:try|"),
    ("self_myself_negated", lexicons, "r\"(?<!not )(?<!n't )(?<!never )(?:try|", "r\"(?:try|"),
    ("ism_can_help_dropped", lexicons, 'r"i can (?:certainly |definitely |surely |absolutely |also )?help",', ""),
    ("ism_else_dropped", lexicons, 'r"(?:is there|would you like(?: me)?', 'r"zzqq(?:is there|would you like(?: me)?'),
    ("ism_else_to_dropped", lexicons, 'r"anything else (?:to (?:add|adjust|know|discuss|ask)|',
     'r"zzqq (?:to (?:add|adjust|know|discuss|ask)|'),
    ("meta_pointing_dropped", lexicons, 'r"pointing back to (?:when|what)", ', ""),
    ("meta_question_dropped", lexicons, ', r"ask(?:s|ing)? for it in a question"', ""),
    ("forgot_re_dropped", lexicons, 'FORGOT_RE = _alt([r"i(?:\'ve| have)? forgot(?:ten)?", ', "FORGOT_RE = _alt(["),
    ("self_err_correct_dropped", lexicons, 'SELF_ERR_RE = _alt([r"correct(?:ing|ed) me", ', "SELF_ERR_RE = _alt(["),
    ("self_err_meant_to", lexicons, 'r"i meant(?! to)"', 'r"i meant"'),
    ("earlier_re_dropped", lexicons, 'EARLIER_RE = _alt([r"(?:mentioned|said|', 'EARLIER_RE = _alt([r"zzqq(?:mentioned|said|'),
    ("live_it_is_dropped", lexicons, 'LIVE_RE = re.compile(r"(?<![a-z])(?:(?:it is|', 'LIVE_RE = re.compile(r"(?<![a-z])(?:(?:zzqq|'),
    ("live_weather_is_dropped", lexicons, '|the weather (?:is|has been|looks)\\b', '|zzqq (?:is|has been|looks)\\b'),
    ("run_on_join_empty", lexicons, 'RUN_ON_JOIN = {"so", ', 'RUN_ON_JOIN = {"zzqq", '),
]
