"""Round 4 checker mutants (2026-10-04; fixtures_r4.py): each reverts or overshoots one round 4 change. Same form as
checker_mutants.SRC, (name, module, old, new); checker_mutants appends this list. Parts no fixture can reach cheaply
(the everyday-word values ASSIST_CASE leaves out, the idiom heads PERSPECTIVE skips, the lookup-value exemption of
"never said") are pinned and mutated by the unit tests (tests/test_round4_fixes.py, unit-test mutant run)."""
import check_r4
import lexicons
import lexicons_r4

SRC_R4 = [
    ("never_off", check_r4, "m = L4.USER_SAID_RE.search(sent)", "m = None"),
    ("never_user_said_ignored", check_r4,
     'if vals and not any(_user_said(ctx, v, i) or R3._first_source(ctx, v, i) == "tool" for v in vals):',
     "if vals:"),
    ("never_no_clause_split", check_r4, "for sent in (c for x in sentences(s) for c in SELF_CLAUSE.split(x)):",
     "for sent in sentences(s):"),
    ("remember_off", check_r4, "m = L4.REMEMBER_RE.search(s) if not", "m = None if True else 0 if not"),
    ("remember_prev_line_ok", check_r4, "if vals and not R3._said_before(ctx, vals, i - 1):",
     "if vals and not R3._said_before(ctx, vals, i):"),
    ("remember_any_distance", check_r4, "if vals and not R3._said_before(ctx, vals, i - 1):", "if vals:"),
    ("remember_promise_too", lexicons_r4, 'REMEMBER_RE = _alt([r"i (?:do ', 'REMEMBER_RE = _alt([r"i(?:\'ll)? (?:do '),
    ("earlier_r3_words", lexicons, 'EARLIER_RE = _alt([_SAYV + r"(?: [\\w\']+){0,6} " + _EARLY,',
     'EARLIER_RE = _alt([r"(?:mentioned|said|told me|shared|brought up|talked about)(?: [\\w\']+){0,6} (?:earlier|'
     'before|previously)",'),
    ("short_lead_in_meta_dropped", lexicons, ',\n                      r"(?:a|with) short lead in"])', "])"),
    ("first_person_off", check_r4, "m = rx.search(s) if rx else None", "m = None"),
    ("first_person_you_literal", check_r4, "parts.append(FIRST_PERSON.get(w, re.escape(w)))",
     "parts.append(re.escape(w))"),
    ("first_person_no_key_masks", check_r4, "    for x in key_masks(skel):", "    for x in []:"),
    ("ask_me_lead_off", check_r4, 'if lead and re.match(r"\\s*ask\\b", g, re.I):', "if False:"),
    ("case_names_off", check_r4, "if not m.group(0).startswith(v)), None)", "if False), None)"),
    ("third_person_off", check_r4, "m = next((m for rx in rxs for m in [rx.search(s)] if m), None)", "m = None"),
    ("third_person_comma_too", check_r4, 'r"\\s+" + L4.THIRD_VERB', 'r"\\W+" + L4.THIRD_VERB'),
    ("claims_off", check_r4, "m = next((m for rx in pats for m in [rx.search(s)] if m), None)", "m = None"),
    ("rule_stated_off", check_r4, 'if rx and i in ctx.text and ctx.by_i[i]["mode"] == "guided"',
     'if False and rx and i in ctx.text and ctx.by_i[i]["mode"] == "guided"'),
    ("rule_one_sentence_loose", lexicons_r4, 'RULE_STATES = {"one_sentence": _alt([r"(?:one|single|1) sentences?"',
     'RULE_STATES = {"one_sentence": _alt([r"(?:one|single|1) sentences?|rule"'),
    ("relation_off", check_r4, "if m and m.group(1).lower() in rels and m.group(1).lower() != r.lower():",
     "if False:"),
    ("relation_same_fires", check_r4, "if m and m.group(1).lower() in rels and m.group(1).lower() != r.lower():",
     "if m and m.group(1).lower() in rels:"),
    ("relation_gap_0", lexicons_r4, "REL_GAP = 3", "REL_GAP = 0"),
    ("relation_gap_1", lexicons_r4, "REL_GAP = 3", "REL_GAP = 1"),
    ("job_off", check_r4, "hit = hit or (m and m.group(0))", "hit = hit"),
    ("job_adjective_fires", check_r4, '+ "|".join(sorted(rels)) + r")(?![a-z]))", s, re.I)',
     '+ "zzz" + r")(?![a-z]))", s, re.I)'),
    ("service_off", check_r4, "if not t.get(\"lookup_call\") and L4.SERVICE_RE.search(s)]",
     "if False]"),
    ("service_ready_dropped", lexicons_r4, r'r"ready to (?:help|assist)", ', ""),
    ("service_glad_dropped", lexicons_r4, r'r"glad (?:i could|to) (?:help|assist)",', ""),
    ("service_certainly_do_dropped", lexicons_r4, r'r"i can (?:certainly|definitely|surely|absolutely) do that", ', ""),
    ("service_here_to_dropped", lexicons_r4, r'SERVICE_RE = _alt([r"here to (?:help|assist|support)", ',
     "SERVICE_RE = _alt(["),
    ("service_else_question_dropped", lexicons_r4, r'r"at your service", r"anything else\s*\?",',
     r'r"at your service",'),
    ("service_here_to_answer_dropped", lexicons_r4, 'here to (?:listen|answer)",', 'here to (?:zzqq)",'),
    ("service_what_else_dropped", lexicons_r4, r'r"what else can i (?:help|do|assist)"', r'r"zzqq"'),
    ("service_happy_helps_dropped", lexicons_r4, r'r"(?:happy|glad) to help\w+", ', ""),
    ("service_anything_more_dropped", lexicons_r4, r'r"(?:know|add|need|discuss|share) anything (?:else|more|extra)",',
     ""),
    ("service_in_mind_dropped", lexicons_r4, r'r"anything else in mind", ', ""),
    ("service_of_service_dropped", lexicons_r4, r'r"be of service", ', ""),
    ("service_try_help_dropped", lexicons_r4, r'r"i can try to help",', ""),
    ("service_anything_new_dropped", lexicons_r4, 'is there anything (?:new|more|you need', 'is there anything (?:zzqq'),
]
