"""RC-12 mutants of the runner / scoring / fake machinery (mutation_e2e.py). Each is (module, old text, new text,
the claim it breaks). A mutant is KILLED when validate_e2e.gates() plus validate_machinery.checks() report a
different set of failures than the unmutated baseline; it must not crash. Pure data."""

GATED = 'score=float(r["unit"] == 1.0 and c.get("unit") == 1.0 and not c.get("cf_unswapped"))))'
OLD_LIST_RULE = (r'spans = [(k, m.span(2), m.group(2)) for k, m in enumerate(FD.re.match('
                 r'r"^(\s*(?:\d+[.)]|[-*\u2022])\s+)(.*)$", s) for s in text.split("\n")) if m]')

MUTANTS = [
    # runner.py: the feedback loop, stop rule, truncation accounting, HF refusal
    ("runner", 'msgs.append({"role": "assistant", "content": text})',
     'msgs.append({"role": "assistant", "content": rec["turns"][t["i"] - 1]["ideal"]})',
     "history gets the IDEAL reply instead of the model's own"),
    ("runner", "text = text.strip()", "text = text", "fed-back reply not stripped"),
    ("runner", 'if render == "plain":', "if False:", "plain stop rule not applied"),
    ("runner", 'stop = "role"', "stop = stop", "role cut not recorded as the stop reason"),
    ("runner", "if lost:", "if False:", "truncated probes not failed"),
    ("runner", 'NEEDED_KINDS = ("S", "C", "I", "O", "Q", "T")', 'NEEDED_KINDS = ("S", "C")',
     "needed turn kinds narrowed"),
    ("runner", 'if i <= played[probe["turn"] - 1]["dropped"]', 'if i < played[probe["turn"] - 1]["dropped"]',
     "dropped-turn off by one"),
    ("runner", "budget = None if ctx is None else ctx - RD.MAX_NEW_TOKENS", "budget = None if ctx is None else ctx",
     "no room kept for the 256 new tokens"),
    ("runner", "hist, dropped = RD.fit(msgs, budget, lambda m: responder.count(m, render))",
     "hist, dropped = RD.fit(msgs, budget, lambda m: responder.count(m, render))[0], 0",
     "history truncated but the drop not recorded"),
    ("runner", 'g["unit"] = G.unit_score(rec, g["probes"])', "pass", "unit not recomputed after truncation"),
    ("runner", "if not args.hf_untested_ok:", "if False:", "untested HF path runs without the flag"),
    # render.py
    ("render", 'return "\\n".join(lines) + "\\nAssistant:"', 'return "\\n".join(lines)',
     "plain render without the generation tag"),
    ("render", r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:", re.I)',
     r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:")', "role cut case-sensitive"),
    ("render", r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:", re.I)',
     r'ROLE_CUT = re.compile(r"[ \t]*(?:user|assistant|human)[ \t]*:", re.I)', "role cut without the newline"),
    ("render", "kept = kept[2:]", "kept = kept[1:]", "fit drops half pairs"),
    ("render", "while len(kept) > 1 and count(kept) > budget:", "while len(kept) > 1 and count(kept) > budget + 100:",
     "fit overshoots the budget"),
    ("render", "m = history[2 * k + 1]", "m = history[2 * k]", "own_reply off by one"),
    # score.py
    ("score", 'score=float(all(t["unit"] == 1.0 for t in twins))))',
     'score=sum(t["unit"] for t in twins) / 2))', "BIND scored per conversation, not per pair"),
    ("score", "if (f, c) not in DIAG:", "if True:", "COMPOSE counted in TWOHOP"),
    ("score", 'COMPOSITE = ["RECALL", "CORR",', 'COMPOSITE = ["T0", "RECALL", "CORR",', "T0 in the composite"),
    ("score", "return mean(mean(v) for v in by_train.values())",
     "return mean(x for v in by_train.values() for x in v)", "flat mean instead of nested seed means"),
    ("score", "seeds = sampled or {None}", "seeds = {None}", "greedy scored when sampling seeds exist"),
    ("score", 'loop_rate=degen.get("LOOP")', 'loop_rate=degen.get("RUNAWAY")', "loop rate counts runaways"),
    ("score", "BARS = dict(level_a=0.80,", "BARS = dict(level_a=0.50,", "Level A bar lowered"),
    ("score", "loop=0.02,", "loop=0.10,", "loop bar raised"),
    ("score", "met=comparator_loop is not None and loop_rate <= comparator_loop)", "met=True)",
     "loop-vs-comparator always met"),
    ("score", 'claimable = met and n_train >= BARS["min_train_seeds"]', "claimable = met",
     "claimable with one training seed"),
    ("score", '"CORR:U": ("CORR", ("U-diff", "U-same"))', '"CORR:U": ("CORR", ("U-same",))', "CORR:U without U-diff"),
    ("score", "and k not in keys:", "and k != f:", "Level A keys double-count cell units"),
    # score_stats.py
    ("score_stats", "HEADROOM = dict(floor=0.05,", "HEADROOM = dict(floor=0.0,", "headroom floor bar"),
    ("score_stats", "ceiling=0.95)", "ceiling=1.01)", "headroom ceiling bar"),
    ("score_stats", "diffs.append(_r(aa, draw, rng) - _r(ab, draw, rng))",
     "diffs.append(_r(aa, draw, rng) - _r(ab, {f: [rng.randrange(len(uids[f])) for _ in uids[f]] "
     "for f in S.COMPOSITE}, rng))", "bootstrap not paired"),
    ("score_stats", "LEVEL_R_MARGIN = -3.0", "LEVEL_R_MARGIN = -300.0", "Level R margin"),
    ("score_stats", 'if r["family"] != "PERSIST"', "if True", "PERSIST replies counted in base rates"),
    ("score_stats", "PERSIST_DROP = 0.30", "PERSIST_DROP = 1.0", "PERSIST drop bar"),
    ("score_stats", 'if comparator["families"][f] > HEADROOM["floor"]]', "if True]", "sensitivity drops nothing"),
    # fakes: a stronger cheater must turn a gate red
    ("fakes", 'name = "ECHO"\n\n    def probe(self, history, t, p):\n        return t["text"]',
     'name = "ECHO"\n\n    def probe(self, history, t, p):\n        return t["ideal"]', "ECHO answers right"),
    ("fakes", 'v = QS.picks(self.rec, dict(p, pool_values=p["lure_items"]) if is_list else p).get(self.rule)',
     'v = p.get("gold") or QS.picks(self.rec, dict(p, pool_values=p["lure_items"]) if is_list else p).get(self.rule)',
     "value cheaters get the gold"),
    ("fakes", "v = self.own_value(history, p)", 'v = p.get("ideal_gold")',
     "IDEAL answers OWN from the annotation, not its own reply"),
    ("fakes", "return SWAP_RX.sub(rep, text)", "return text", "USERVOICE keeps the assistant voice"),
    ("fakes", "        return ABSTAIN\n", '        return p["ideal"]\n', "ABSTAIN answers right"),
    ("fakes_family", 'if not active or self.policy == "never":', "if not active:", "P_NEVER obeys"),
    ("fakes_family", "            return prev\n", '            return t["ideal"]\n', "L_REPEAT does not loop"),
    ("fakes_family", "for _, rule, arg in reversed(active):", "for _, rule, arg in active:",
     "P_OBEYALL lets the newest rule win (correct on 3 of 4 override pairs)"),
    ("hf_responder", "\nHF_TESTED = False\n", "\nHF_TESTED = True\n", "HF path claims to be tested"),
    # step 5 audit: the audit cheaters and the OWN counterfactual diagnostic
    ("fakes_audit", "v = AR.rule_picks(self.rec, q).get(ALIAS.get(self.rule, self.rule))",
     'v = p.get("gold") or AR.rule_picks(self.rec, q).get(ALIAS.get(self.rule, self.rule))',
     "audit value cheaters get the gold"),
    ("fakes_audit", "            if first:\n                return F.ABSTAIN\n",
     '            if p["grader"] == "ABS":\n                return F.ABSTAIN\n', "ORDER_ABS abstains where it should"),
    ("own_cf", "new = _exchange(text, picked[0], opts[(opts.index(picked[0]) + 1) % len(opts)])", "new = text",
     "OWN-CF pick not swapped"),
    ("own_cf", "lines[ka], lines[kb] = la[:a0] + lb[b0:b1] + la[a1:], lb[:b0] + la[a0:a1] + lb[b1:]", "pass",
     "OWN-CF list not swapped"),
    ("runner", 'alt = OC.swap(rec, t["i"], text) if own_cf else None', "alt = None", "runner ignores --own-cf"),
    # OD1 (b), 2026-09-25: the OWN gate over the own-history and --own-cf runs (validate_machinery.c_owngate)
    ("score", GATED, 'score=r["unit"]))', "OD1 b: the AND replaced by the own-history result alone"),
    ("score", "gated = bool(own) and all(twin(r, cf) is not None for r in own)", "gated = bool(own)",
     "OD1 b: a run missing --own-cf twins still gets a gated OWN"),
    ("score", 'if set(per.get("OWN_GATED", {})) != set(per.get("OWN", {})):', "if False:",
     "OD1 b: gated OWN from only the runs that have cf rows"),
    ("score", 'rows = [r for r in sel if not r.get("own_cf")]', "rows = sel",
     "OD1 b: cf rows counted in the loop rate and diagnostics"),
    ("score", 'if r.get("own_cf"):', "if False:", "OD1 b: cf rows counted as own-history units"),
    ("score", "fam = {f: ks.get(GATE.get(f, f)) for f in COMPOSITE}", "fam = {f: ks.get(f) for f in COMPOSITE}",
     "OD1 b: R uses the ungated OWN"),
    ("score_stats", 'and u["family"] not in S.GATE and', 'and u["family"] not in S.SLOT and',
     "OD1 b: bootstrap OWN slot takes the ungated units"),
    ("score_stats", "assert all(uids.values()),", "assert True,", "OD1 b: bootstrap runs without the cf rows"),
    ("score_stats",
     'vals = {m: s["families"][k] if k in s["families"] else s["keys"].get(k) for m, s in panel.items()}',
     'vals = {m: s["keys"].get(k) for m, s in panel.items()}', "OD1 b: headroom judges the ungated OWN"),
    ("score_stats", 'if any(s["families"][f] is None for s in (summary, comparator) for f in S.COMPOSITE):',
     "if False:", "OD1 b: sensitivity row computed with OWN missing"),
    ("score_stats", ' and not r.get("own_cf")\n', "\n", "OD1 b: cf replies counted in PERSIST base rates"),
    # OD6 (iii), 2026-09-25: statement-turn repeats are ack-repeats, reported beside the loop rate
    # (validate_machinery.c_ackrep)
    ("score", "hits = sum(a is True for a in stated)", "hits = 0", "OD6 iii: ack-repeats never counted"),
    ("score", "(hits / len(stated) if stated else None)", "(hits / len(marks) if stated else None)",
     "OD6 iii: ack-repeat-of-statements rate over every reply"),
    ("score", 'level_a(ks, degen.get("LOOP"),', 'level_a(ks, degen.get("LOOP") + ack_all,',
     "OD6 iii: ack-repeats counted in the Level A loop criterion"),
    ("runner", 'ack_repeat=g["ack_repeat"], ack_of_answer=', "ack_of_answer=",
     "OD6 iii: runner drops the ack-repeat record"),
    ("fakes_family", 'return "Got it." if t["kind"] in ("S", "L", "C", "I", "O", "T") else',
     'return "Got it." if t["kind"] in ("S", "L", "C", "I", "O", "T", "D") else',
     "OD6 iii: ACKER also acks D questions (those repeats are LOOPs)"),
    # verifier 2026-09-25: the OD1 b gate (validate_machinery c_owncf, c_owngate) and the OD6 reports (c_ackrep)
    ("score", GATED, 'score=float(c.get("unit") == 1.0 and not c.get("cf_unswapped"))))',
     "OD1 b: the gate takes the cf result alone (NEXT passes)"),
    ("score", GATED, 'score=float(r["unit"] == 1.0) * (sum(x["unit"] for x in cf.values()) / len(cf))))',
     "OD1 b: product of rates (own-history unit x the cf run's rate)"),
    ("score", 'cf = {r["id"]: r for r in run_rows if r.get("own_cf") and r["family"] == "OWN"}',
     'cf = dict(zip(reversed([r["id"] for r in run_rows if r["family"] == "OWN" and not r.get("own_cf")]), '
     '[r for r in run_rows if r.get("own_cf") and r["family"] == "OWN"]))',
     "OD1 b: misaligned join (cf rows zipped to the own ids in reverse order)"),
    ("score", GATED, 'score=float(r["unit"] == 1.0 and c.get("unit") == 1.0)))',
     "OD1 b: a cf rewrite that did not take still counts"),
    ("score", '(c.get("responder"), c.get("render")) == (r.get("responder"), r.get("render"))',
     'c.get("render") == r.get("render")', "OD1 b: a cf run of another responder is a twin"),
    ("score", '(c.get("responder"), c.get("render")) == (r.get("responder"), r.get("render"))',
     'c.get("responder") == r.get("responder")', "OD1 b: a cf run in another render is a twin"),
    ("score", 'sampled = {r["seed"] for r in rows if r["seed"] is not None and not r.get("own_cf")}',
     'sampled = {r["seed"] for r in rows if r["seed"] is not None}', "OD1 b: cf rows choose the seeds"),
    ("runner", 'out[-1]["cf_unswapped"] = True', "pass", "OD1 b: runner does not mark a cf rewrite that did not take"),
    ("runner", 'cf_unswapped=any(x.get("cf_unswapped") for x in played))', "cf_unswapped=False)",
     "OD1 b: the row drops the cf_unswapped mark"),
    ("own_cf", "return new if _picked(new, opts) == [opts[(opts.index(picked[0]) + 1) % len(opts)]] else UNSWAPPED",
     "return new", "OD1 b: a pick rewrite that did not take passes as swapped"),
    ("own_cf", "spans = FD.list_spans(T.norm(text))", OLD_LIST_RULE,
     "OD1 b: own_cf finds list lines with a looser rule than G-DYN (the pre-fix ITEM rule)"),
    ("score", "ack_all, ack_stated = ack_stats(rows)", "ack_all, ack_stated = ack_stats(sel)",
     "OD6 iii: --own-cf rows counted in the ack-repeat rates"),
    ("score", "ack_repeat_of_answers=answer_repeat_stats(rows)", "ack_repeat_of_answers=answer_repeat_stats(sel)",
     "OD6 iii: --own-cf rows counted in the answer-repeat rate"),
    ("score", "return sum(a is True for a in marks) / len(marks) if marks else None", "return 0.0 if marks else None",
     "OD6 iii: answer repeats never counted"),
    ("runner", 'ack_of_answer=g["ack_of_answer"], ', "", "OD6 iii: runner drops the answer-repeat record"),
    # F1, decided 2026-09-25 (prereg draft s17 OD6 follow-up): a statement-turn reply equal to an earlier reply to
    # an asking turn is a LOOP; ack after ack stays exempt (validate_machinery.c_ackrep: PARROT, ACKER)
    ("grade_loop", "return [p for p, k in zip(prior_ws, prior_kinds) if asks(k)]", "return []",
     "F1: parroted answers exempt again (PARROT meets the Level A loop criterion)"),
    ("grade_loop", "return [p for p, k in zip(prior_ws, prior_kinds) if asks(k)]", "return prior_ws",
     "F1: ack after ack charged again (ACKER loops)"),
    # F2, decided 2026-09-25 (prereg draft s17 OD6 follow-up (2)): a small-talk D filler (asks: false) is a statement
    # turn for the loop rule (validate_machinery.c_ackrep: SMALLTALK; PARROT and the denominators read the record)
    ("grade_loop", 'return "D" if t["asks"] else "d"', 'return "D"',
     "F2: small-talk fillers ask again (SMALLTALK loops)"),
    ("fakes_family", 'return t["kind"] in "PXQ" or (t["kind"] == "D" and t["asks"])', 'return t["kind"] in "PXQD"',
     "F2: the machinery checks read every D turn as asking (their expected counts ignore the annotation)"),
    # verifier 2026-09-25 (round 2): the F3 / strict case (d) measurement (score.equality_only, graders.eq_only;
    # validate_machinery.c_ackrep: RESTATE, TERSE_VAL, TERSE_VAL_CTRL, IDEAL)
    ("score", 'out[f][0] += p["eq_only"] is True', 'out[f][0] += not p["ok"]',
     "F3 report: every failing probe counted as equality-only (RESTATE's self-copies too)"),
    ("score", "equality_only=equality_only_stats(rows),", "equality_only=equality_only_stats(sel),",
     "F3 report: --own-cf rows counted"),
    ("fakes_family", 'if p is None or self.name == "TERSE_VAL_CTRL":', "if p is None:",
     "F3: the control fake confirms with the bare gold too (it loops)"),
]
