"""RC-12 mutants of the runner / scoring / fake machinery (mutation_e2e.py). Each is (module, old text, new text,
the claim it breaks). A mutant is KILLED when validate_e2e.gates() plus validate_machinery.checks() report a
different set of failures than the unmutated baseline; it must not crash. Pure data."""

MUTANTS = [
    # runner.py: the feedback loop, stop rule, truncation accounting, HF refusal
    ("runner", 'msgs.append({"role": "assistant", "content": text})',
     'msgs.append({"role": "assistant", "content": rec["turns"][t["i"] - 1]["ideal"]})',
     "history gets the IDEAL reply instead of the model's own"),
    ("runner", "text = text.strip()", "text = text", "fed-back reply not stripped"),
    ("runner", 'if render == "plain":', "if False:", "plain stop rule not applied"),
    ("runner", 'stop = "role"', "stop = stop", "role cut not recorded as the stop reason"),
    ("runner", "if lost:", "if False:", "truncated probes not failed"),
    ("runner", 'NEEDED_KINDS = ("S", "C", "I", "O", "Q", "T")', 'NEEDED_KINDS = ("S", "C")',
     "needed turn kinds narrowed"),
    ("runner", 'if i <= played[probe["turn"] - 1]["dropped"]', 'if i < played[probe["turn"] - 1]["dropped"]',
     "dropped-turn off by one"),
    ("runner", "budget = None if ctx is None else ctx - RD.MAX_NEW_TOKENS", "budget = None if ctx is None else ctx",
     "no room kept for the 256 new tokens"),
    ("runner", "hist, dropped = RD.fit(msgs, budget, lambda m: responder.count(m, render))",
     "hist, dropped = RD.fit(msgs, budget, lambda m: responder.count(m, render))[0], 0",
     "history truncated but the drop not recorded"),
    ("runner", 'g["unit"] = G.unit_score(rec, g["probes"])', "pass", "unit not recomputed after truncation"),
    ("runner", "if not args.hf_untested_ok:", "if False:", "untested HF path runs without the flag"),
    # render.py
    ("render", 'return "\\n".join(lines) + "\\nAssistant:"', 'return "\\n".join(lines)',
     "plain render without the generation tag"),
    ("render", r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:", re.I)',
     r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:")', "role cut case-sensitive"),
    ("render", r'ROLE_CUT = re.compile(r"\n[ \t]*(?:user|assistant|human)[ \t]*:", re.I)',
     r'ROLE_CUT = re.compile(r"[ \t]*(?:user|assistant|human)[ \t]*:", re.I)', "role cut without the newline"),
    ("render", "kept = kept[2:]", "kept = kept[1:]", "fit drops half pairs"),
    ("render", "while len(kept) > 1 and count(kept) > budget:", "while len(kept) > 1 and count(kept) > budget + 100:",
     "fit overshoots the budget"),
    ("render", "m = history[2 * k + 1]", "m = history[2 * k]", "own_reply off by one"),
    # score.py
    ("score", 'score=float(all(t["unit"] == 1.0 for t in twins))))',
     'score=sum(t["unit"] for t in twins) / 2))', "BIND scored per conversation, not per pair"),
    ("score", "if (f, c) not in DIAG:", "if True:", "COMPOSE counted in TWOHOP"),
    ("score", 'COMPOSITE = ["RECALL", "CORR",', 'COMPOSITE = ["T0", "RECALL", "CORR",', "T0 in the composite"),
    ("score", "return mean(mean(v) for v in by_train.values())",
     "return mean(x for v in by_train.values() for x in v)", "flat mean instead of nested seed means"),
    ("score", "seeds = sampled or {None}", "seeds = {None}", "greedy scored when sampling seeds exist"),
    ("score", 'loop_rate=degen.get("LOOP")', 'loop_rate=degen.get("RUNAWAY")', "loop rate counts runaways"),
    ("score", "BARS = dict(level_a=0.80,", "BARS = dict(level_a=0.50,", "Level A bar lowered"),
    ("score", "loop=0.02,", "loop=0.10,", "loop bar raised"),
    ("score", "met=comparator_loop is not None and loop_rate <= comparator_loop)", "met=True)",
     "loop-vs-comparator always met"),
    ("score", 'claimable = met and n_train >= BARS["min_train_seeds"]', "claimable = met",
     "claimable with one training seed"),
    ("score", '"CORR:U": ("CORR", ("U-diff", "U-same"))', '"CORR:U": ("CORR", ("U-same",))', "CORR:U without U-diff"),
    ("score", "and k not in keys:", "and k != f:", "Level A keys double-count cell units"),
    # score_stats.py
    ("score_stats", "HEADROOM = dict(floor=0.05,", "HEADROOM = dict(floor=0.0,", "headroom floor bar"),
    ("score_stats", "ceiling=0.95)", "ceiling=1.01)", "headroom ceiling bar"),
    ("score_stats", "diffs.append(_r(aa, draw, rng) - _r(ab, draw, rng))",
     "diffs.append(_r(aa, draw, rng) - _r(ab, {f: [rng.randrange(len(uids[f])) for _ in uids[f]] "
     "for f in S.COMPOSITE}, rng))", "bootstrap not paired"),
    ("score_stats", "LEVEL_R_MARGIN = -3.0", "LEVEL_R_MARGIN = -300.0", "Level R margin"),
    ("score_stats", 'if r["family"] != "PERSIST"', "if True", "PERSIST replies counted in base rates"),
    ("score_stats", "PERSIST_DROP = 0.30", "PERSIST_DROP = 1.0", "PERSIST drop bar"),
    ("score_stats", 'if comparator["families"][f] > HEADROOM["floor"]]', "if True]", "sensitivity drops nothing"),
    # fakes: a stronger cheater must turn a gate red
    ("fakes", 'name = "ECHO"\n\n    def probe(self, history, t, p):\n        return t["text"]',
     'name = "ECHO"\n\n    def probe(self, history, t, p):\n        return t["ideal"]', "ECHO answers right"),
    ("fakes", 'v = QS.picks(self.rec, dict(p, pool_values=p["lure_items"]) if is_list else p).get(self.rule)',
     'v = p.get("gold") or QS.picks(self.rec, dict(p, pool_values=p["lure_items"]) if is_list else p).get(self.rule)',
     "value cheaters get the gold"),
    ("fakes", "v = self.own_value(history, p)", 'v = p.get("ideal_gold")',
     "IDEAL answers OWN from the annotation, not its own reply"),
    ("fakes", "return SWAP_RX.sub(rep, text)", "return text", "USERVOICE keeps the assistant voice"),
    ("fakes", "        return ABSTAIN\n", '        return p["ideal"]\n', "ABSTAIN answers right"),
    ("fakes_family", 'if not active or self.policy == "never":', "if not active:", "P_NEVER obeys"),
    ("fakes_family", "            return prev\n", '            return t["ideal"]\n', "L_REPEAT does not loop"),
    ("fakes_family", "for _, rule, arg in reversed(active):", "for _, rule, arg in active:",
     "P_OBEYALL lets the newest rule win (correct on 3 of 4 override pairs)"),
    ("hf_responder", "\nHF_TESTED = False\n", "\nHF_TESTED = True\n", "HF path claims to be tested"),
    # step 5 audit: the audit cheaters and the OWN counterfactual diagnostic
    ("fakes_audit", "v = AR.rule_picks(self.rec, q).get(ALIAS.get(self.rule, self.rule))",
     'v = p.get("gold") or AR.rule_picks(self.rec, q).get(ALIAS.get(self.rule, self.rule))',
     "audit value cheaters get the gold"),
    ("fakes_audit", "            if first:\n                return F.ABSTAIN\n",
     '            if p["grader"] == "ABS":\n                return F.ABSTAIN\n', "ORDER_ABS abstains where it should"),
    ("own_cf", "return _exchange(text, picked[0], opts[(opts.index(picked[0]) + 1) % len(opts)])", "return text",
     "OWN-CF pick not swapped"),
    ("own_cf", "lines[idx[1]], lines[idx[2]] = ma.group(1) + mb.group(2), mb.group(1) + ma.group(2)", "pass",
     "OWN-CF list not swapped"),
    ("runner", 'alt = OC.swap(rec, t["i"], text) if own_cf else None', "alt = None", "runner ignores --own-cf"),
]
