"""RC-12 DEV fillers, part B (SPEC s1 Fillers): small talk and tiny creative requests. Same rules as part A
(pools_fill_a.py). The IDEAL replies of the creative requests are single sentences too."""

FILLERS_B = [
    ("I finally repotted all my succulents this afternoon.",
     "That sounds like a satisfying afternoon, and they will enjoy the fresh soil."),
    ("I'm feeling a bit nervous about a presentation coming up.",
     "That is completely normal, and a couple of practice runs out loud usually takes the edge off."),
    ("I just finished a really good mystery novel.",
     "Nice, there is nothing quite like a twist you did not see coming."),
    ("It's been raining nonstop here all week.",
     "That can get gloomy, so a warm drink and a good film might help pass the evenings."),
    ("I tried a new hiking trail this morning.",
     "That sounds great, a new trail always makes the familiar outdoors feel fresh again."),
    ("I've been sleeping much better lately.",
     "That is wonderful news, good sleep makes almost everything else easier."),
    ("I managed to fix the leaky faucet myself.",
     "Well done, small repairs like that save money and feel really satisfying."),
    ("I'm thinking about learning to paint with watercolors.",
     "That is a lovely hobby to pick up, and simple landscapes are a forgiving place to start."),
    ("Today felt really long for some reason.",
     "Some days just drag, so I hope you get a calm evening to unwind."),
    ("I spotted a hummingbird at the feeder this morning.",
     "How lovely, they are such tiny and quick visitors."),
    ("I cleaned out my inbox for the first time in ages.",
     "That must feel like a weight off your shoulders."),
    ("I'm trying to drink more water during the day.",
     "Carrying a refillable bottle everywhere and sipping whenever you sit down makes that far easier."),
    ("I rearranged the furniture in the living room.",
     "A new layout can make a familiar room feel brand new."),
    ("I've started going for short walks after dinner.",
     "That is a great habit for digestion and for clearing your head."),
    ("I'm a little tired of cooking every night.",
     "Cooking a double batch twice a week can give you a few nights off."),
    ("I found an old photo album in the attic.",
     "What a treat, old photos bring back so many memories."),
    ("The sunrise was really pretty today.",
     "Early mornings like that make getting up worth it."),
    ("I'm finally caught up on laundry.",
     "That is a small victory worth enjoying while it lasts."),
    ("I signed up for an evening pottery class.",
     "How fun, working with clay is relaxing and very hands-on."),
    ("I've been trying to spend less time on my phone.",
     "Keeping it in another room during meals and before bed can make a big difference."),
    ("Compose two rhyming lines about falling leaves.",
     "The leaves let go without a sound, and drift in circles to the ground."),
    ("Give me a riddle that's easy to solve.",
     "What has keys but cannot open a single lock, a piano."),
    ("Write a short haiku about the ocean.",
     "Waves fold into foam, the tide pulls back its long breath, shells wait in the sand."),
    ("Describe a sleepy snail in one sentence.",
     "It naps under a damp leaf with its shell pulled close like a tiny blanket."),
    ("Give me a tongue twister to practice.",
     "Six slick slim sleds slid slowly down the slope."),
    ("Write one line about a quiet morning.",
     "The kettle hums while the whole house is still asleep."),
    ("Describe the smell of rain in one sentence.",
     "It smells earthy and clean, like wet stones and fresh soil after a long dry spell."),
    ("Give me a gentle compliment I could send someone.",
     "You could say that talking with them always leaves you in a better mood."),
    ("Describe a cozy little bookstore in one sentence.",
     "It has creaky floors, a sleepy armchair by the window, and shelves stacked right up to the ceiling."),
    ("Write a one-sentence story about a lost umbrella.",
     "The umbrella rode the bus for three days before a child finally claimed it for a rainy walk home."),
    ("Recommend something soothing for a slow evening.",
     "Try a warm bath, soft music, and a chapter of a book you have been meaning to finish."),
    ("What's a nice way to thank someone for a small favor?",
     "A short handwritten note that mentions exactly how the favor helped you goes a long way."),
    ("Give me an idea for a simple weekend project.",
     "Build a small herb planter from scrap wood and set it on a sunny windowsill."),
    ("What's a fun question to ask at a dinner party?",
     "Ask everyone what small thing made them happiest in the past week."),
    ("Suggest a way to make a boring commute more pleasant.",
     "Pick a long audio series or audiobook that you only let yourself enjoy on the way."),
    ("Give me a short motivational line for a tough day.",
     "You have made it through every hard day so far, and this one is no different."),
    ("After work I struggle to switch off, any ideas?",
     "Change clothes, step outside for ten minutes, and leave work thoughts at the door."),
    ("Suggest a simple stretch for a stiff neck.",
     "Slowly tilt your ear toward your shoulder, hold it gently, and then switch sides."),
    ("Give me a cheerful way to start the morning.",
     "Open the curtains right away, play a favorite song, and drink a glass of water."),
    ("How do I go easier on myself?",
     "Talk to yourself the way you would comfort someone you love who was having a hard time."),
    ("Invent a silly holiday we could celebrate.",
     "How about a day when everyone wears two socks that do not match."),
    ("Describe a thunderstorm in one sentence.",
     "The sky rumbles like a moving truck while sheets of rain hammer the rooftops."),
    ("Help me word a thank-you card.",
     "Mention the specific gift or kindness and say how you plan to use or remember it."),
    ("Suggest a calm activity for a rainy afternoon.",
     "A jigsaw puzzle with a warm drink and quiet music is hard to beat."),
    ("What's a good habit to build this year?",
     "A short walk every day is simple to keep and pays off in mood and energy."),
]
