"""RC-12 DEV fillers, part A (SPEC s1 Fillers): knowledge-light how-to and why requests. Each entry is
(user turn, IDEAL reply). Rules checked by test_gens.py: no names, no digits, no value of any RC-12 pool, no
holder word, no PERSIST rule word; every IDEAL reply is exactly one sentence (no internal full stop, no "?" or
"!") so the PERSIST one-sentence rule can reuse it; 0 word 5-grams shared with E001/E004 filler text."""

FILLERS_A = [
    ("What is it about chopping onions that stings so much?",
     "Slicing breaks cells that give off a vapor, and it forms a mild acid once it touches your tear film."),
    ("Any trick for a stubborn jar lid?",
     "Warm the lid under the tap so it loosens a little, then twist while wearing a dish glove for grip."),
    ("Why does a recording of me sound so unlike my real voice?",
     "Inside your head you also hear your voice through bone, which adds a low warmth the microphone never gets."),
    ("Is there a knack to keeping lenses clear when I walk in from the cold?",
     "Let them warm up in a pocket for a minute first, since fog forms when chilled glass meets humid air."),
    ("What causes yawning, anyway?",
     "Scientists still argue about it, though tiredness, boredom and seeing someone else yawn all set it off."),
    ("Folding a fitted bedsheet defeats me every time, any advice?",
     "Nest each elastic corner inside the next one until you hold a neat rectangle, then fold that flat."),
    ("Best approach for keeping parsley and cilantro perky?",
     "Snip the ends, set the bunch upright in a jar with a little water, and loosely tent a bag over the tops."),
    ("Why do straws seem to snap in two when they sit in a drink?",
     "Light bends as it crosses from liquid to air, so the part under the surface looks shifted."),
    ("Tips on making new vocabulary stick?",
     "Say each new term out loud, write a sentence with it, and revisit it after a day and again after a week."),
    ("What turns tree leaves those warm shades each fall?",
     "As days shorten the trees stop producing the pigment that hides other colors, so those shades finally show."),
    ("How would you ease into getting up earlier?",
     "Move the alarm back by a quarter hour every few days and open the curtains right when you rise."),
    ("A hinge in my place keeps creaking, what quiets it?",
     "Pop out the hinge pin, smear on a little petroleum jelly or light oil, and slide it back."),
    ("Where does all the salt in seawater come from?",
     "Rain slowly wears minerals out of rock, streams carry them to the coast, and they stay behind when water evaporates."),
    ("Any pointers for tidier handwriting?",
     "Relax your grip, slow down, and copy one line of evenly sized letters each morning for a few weeks."),
    ("Why do ears feel blocked during takeoff?",
     "Cabin pressure shifts quickly, and a small tube behind the nose needs a swallow or yawn to even it out."),
    ("What's the right way to look after a heavy iron pan?",
     "Rinse and scrub it without harsh soap, dry it over heat, and rub in a very light film of oil."),
    ("My bread starter looks sluggish, what does it need?",
     "Give it regular meals of flour and water and keep it somewhere steady, not too cold and not too hot."),
    ("Why do the stars seem to flicker at night?",
     "Their light crosses moving pockets of air that bend it back and forth, so it appears to shimmer."),
    ("Studying at home is hard for me, how do I concentrate?",
     "Set a timer for short focused blocks, keep distractions out of reach, and rest properly between blocks."),
    ("Does hot water really sound different from cold when you pour it?",
     "Many people can hear it, because hot water flows more thinly and splashes with a slightly higher pitch."),
    ("Tiny flies keep hovering over my fruit bowl, what helps?",
     "Put out a shallow cup of cider vinegar with a little soap mixed in, and toss anything overripe."),
    ("What makes little bumps rise on my arms when I'm cold?",
     "Tiny muscles tug each hair upright, a reflex that once helped fluffier ancestors trap warmth."),
    ("Ideas for making a cramped bedroom feel roomier?",
     "Keep the floor as clear as possible, hang a big mirror, and pick pale walls and furniture raised on legs."),
    ("How do people get started keeping a diary?",
     "Begin with a few sentences before bed about one moment from the day and how you felt about it."),
    ("Why doesn't frozen water sink?",
     "Water spreads out as it turns solid, which makes the frozen form lighter than the liquid beneath it."),
    ("How should I prep my plants before a week away?",
     "Soak them thoroughly the night before and cluster them together in a shaded spot so they dry slowly."),
    ("Why does sparkling water fizz more in some glasses?",
     "Bubbles grow at tiny scratches and specks, so a slightly worn glass gives them more places to start."),
    ("I keep putting off chores, any way around that?",
     "Promise yourself only five minutes on a single task, because getting going is usually the toughest step."),
    ("Why might knees ache before a change in the weather?",
     "Falling air pressure may let joint tissues swell a touch, and some people notice that as an ache."),
    ("Cables are a mess under my desk, how do I tame them?",
     "Gather them with reusable straps and route them along a desk leg so nothing trails on the floor."),
    ("Some candle drips landed on a tablecloth, how do they come off?",
     "Cover the drips with paper towel and press with a warm iron so the paper soaks up the melted wax."),
    ("What actually makes dough puff up?",
     "Yeast feeds on sugars and gives off gas, and the stretchy dough holds those bubbles in."),
    ("Is there a smart way to make a phone battery last for years?",
     "Avoid deep drains and heat, and unplug it once it is mostly full rather than leaving it charging all night."),
    ("Why do some people sneeze when they step into sunshine?",
     "For some, the nerve signals for sudden brightness and for sneezing seem to overlap a little."),
    ("Guests are coming soon, where do I start tidying?",
     "Clear the surfaces people see first, drop stray items into a basket, and give the bathroom sink a wipe."),
    ("How can I sharpen kitchen knives without hurting myself?",
     "Keep the blade at one low, steady angle on the stone and pull it across in slow, even passes."),
    ("Why do yawns spread from person to person?",
     "Seeing a yawn seems to trigger the same urge in others, possibly as a small social signal."),
    ("Long road trips bore me, how do I make them fun?",
     "Queue up an audiobook, plan a couple of scenic stops, and play word games with whoever rides along."),
    ("Why does my morning brew sometimes turn out harsh?",
     "Water that is too hot or grounds that are too fine draw out more of the bitter compounds."),
    ("A rug keeps creeping across my floor, how do I stop it?",
     "Lay a rubber grip pad underneath, trimmed just a little smaller than the rug itself."),
    ("Why does the moon look huge when it's low in the sky?",
     "It is an illusion, since your brain compares it with trees and rooftops and judges it bigger."),
    ("Is it possible to cook well without following recipes?",
     "Learn a handful of basic methods like roasting and simmering, then taste as you go and adjust."),
    ("Mirrors swap left and right, so why not up and down?",
     "They really reverse front and back, and we interpret that flip as left and right trading places."),
    ("Any fix for sneakers that smell?",
     "Let them dry out fully between wears and shake a spoonful of baking soda inside overnight."),
    ("Stiff new boots are hurting my feet, what should I do?",
     "Wear them around the house with thick socks in short stretches before any long walk outside."),
]
